version: '3.7'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_ANONYMOUS_HIDE_VERSION=true"
    volumes:
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana-dashboards:/var/lib/grafana/dashboards"
    ports: [ "3000:3000" ]

