version: "3.7"
services:
  redpanda-0.local:
    container_name: redpanda-0.local
    image: docker.vectorized.io/vectorized/redpanda:latest
    command:
    - redpanda start
    - --smp 1
    - --overprovisioned
    - --memory 1G
    volumes:
    - ./redpanda-config/redpanda-0:/etc/redpanda
    - ./redpanda-data/redpanda-0:/var/lib/redpanda/data
    ports:
    - 9092:9092
    - 9644:9644
    - 8081:8081
    - 8082:8082

