version: "3.7"
services:
  redpanda-5.local:
    container_name: redpanda-5.local
    image: docker.vectorized.io/vectorized/redpanda:latest
    command:
    - redpanda start
    - --smp 1
    - --overprovisioned
    - --memory 1G
    volumes:
    - ./redpanda-config/redpanda-5:/etc/redpanda
    - ./redpanda-data/redpanda-5:/var/lib/redpanda/data
    ports:
    - 9592:9592
    - 9144:9244
    - 8581:8581
    - 8582:8582

