global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
- job_name: redpanda
  static_configs:
  - targets:
    - redpanda-0.local:9644
    - redpanda-1.local:9744
    - redpanda-2.local:9844
  metrics_path: /public_metrics

